backend:
  name: maps
  branch: main
  repo: "mpolom/maps-archive"
  base_url: "https://decap-proxy.michaelpolom.workers.dev"
  auth_endpoint: /auth
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

site_url: https://bichael.uk/maps

media_folder: assets/uploads

collections:
  - name: maps
    label: Maps
    label_singular: Map
    folder: src/maps
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Date, name: date, widget: datetime }
      - { label: Map Image, name: map_image, widget: image }
    editor:
      visualEditing: true
